#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

source ~/.fzf

# Aliases
alias grep='grep --color=auto'
alias tree='tree -a -I .git'
alias ls='ls --color=auto'
alias dir='dir --color=auto'
alias vdir='vdir --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias sudo='sudo '
alias ls='ls -F -b -t --color=always'

# Functions
function __BASH_PROMPT_STATUS__() {
  es=$?
  if [ $es -ne 0 ]; then
    echo -e "\[\e[32m[$es]\e[0m\]"
  fi
}

function n() {
	if ! which nvim &>/dev/null;then
		if which vim &>/dev/null;then
			vim $@
		fi
		echo "neovim not installed."
		return
	fi

	nvim $@
}

function y() {
	if ! which yazi &>/dev/null; then 
		echo "yazi not installed."
		return
	fi 

	local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
	TERM="xterm-kitty" command yazi "$@" --cwd-file="$tmp"
	IFS= read -r -d '' cwd < "$tmp"
	[ -n "$cwd" ] && [ "$cwd" != "$PWD" ] && builtin cd -- "$cwd"
	rm -f -- "$tmp"
}

function cd(){
	builtin cd "$@"
	echo "$PWD" > "$PWD_CD_FILE"
}

function cdd(){
	command cd "$(cat $PWD_CD_FILE)"
} 

# Environment variables
export PATH="$HOME/.cargo/bin:$HOME/.local/bin:$PATH"
export HYFETCH_DONT_WARN_RUST=1
export PWD_CD_FILE="$HOME/.cache/pwd.tmp"
export PWD_CD_HISTORY="$(cat $PWD_CD_FILE)"
export HISTSIZE=1000
export HISTFILESIZE=2000
PS1="\# \[\e[32;1m\][\u@\h]\[\e[34;1m\] \w $(__BASH_PROMPT_STATUS__)\[\e[0m\]$ "

# Bindings
bind 'set show-all-if-ambiguous on'
bind 'TAB:menu-complete'
bind '"\C-h": beginning-of-line'
bind '"\C-l": end-of-line'

# Misc
touch ~/.cache/pwd.tmp 

# Exit if not running TMUX 
[[ ! $TMUX_SF ]] && return


# Load TMUX config
TMUX_PATH="/tmp/tmux.conf"
read -r -d '' TMUX_CONFIG << EOF
set -g mouse on
set -g default-command "bash"

set -g default-terminal "xterm-256color"
set -ga terminal-overrides ",st:RGB"
set -gq allow-passthrough all
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set-option -g status-justify right
set -g bell-action none
set -g status-justify right
set -g status-position top
set -g status-left ''
set -g status-left-length 15
set -g status-right ''
set -g status-right-length 50
set -g default-command "${SHELL}"
unbind-key -n C-Left
unbind-key -n C-Right  
unbind-key -n C-Up
unbind-key -n C-Down
bind-key h select-pane -L # move left
bind-key j select-pane -D # move down
bind-key k select-pane -U # move up
bind-key l select-pane -R # move right
set -g focus-events on
set -g status-style bg=default
set -g status-left-length 99
set -g status-right-length 99
set -g status-justify absolute-centre
EOF

TMUX_PATH="/tmp/tmux.conf"
PROMPT_BOTTOM=0
echo "$TMUX_CONFIG" > "$TMUX_PATH"
tmux source-file "$TMUX_PATH" &>/dev/null

# Handle startup
if [ -n "$TMUX" ];then 
	source ~/.cache/wal/colors.sh &>/dev/null

	# Greet user on first pane in tab
	pane_index=$(tmux display-message -p '#{pane_index}') &>/dev/null
	[ -n "$pane_index" ] && { 
		[ "$pane_index" = "0" ] && {
			echo -e "\033[1;1H"
			hyfetch --args "--structure logo" > /tmp/logo
			fastfetch | lolcat
			echo -e "\033[1;1H"
			cat /tmp/logo
			
			# go to bottom of prompt
			[ $PROMPT_BOTTOM = 1 ] && {
				tput cup $(echo "$(tput lines)-2" | bc) 0 
			} || echo -e "\n\n"
		} 
		notify-send "Opened new tmux pane $pane_index"
	}

	# Load shell features
	source -- ~/.local/share/blesh/ble.sh 
	which zoxide &>/dev/null && eval "$(zoxide init bash)" &
elif [[ ! "$ZSH_ISOLATE" =  "1" ]];then
	tmux -f "$TMUX_PATH" -u new -A -D
	exit
fi
